version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "02:00"
    open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@openzeppelin/contracts"
